### ISSUE TITLE
Cutting GitHub Releases

### ISSUE THREAD

**Issue by anfleene** [innotop/innotop#102]
Hi! Thanks for creating/maintaing an awesome tool. 

Are you all planning to cut releases on GitHub? It looks like you're no longer using google code. If so would it be possible to create a 1.9.1 or newer release? I'm planning to write an innotop chef cookbook and I'd like to build innotop off artifacts that will be used going forward.

**Comment by lefred** [comment]
Currently we don't plan to have new release numbers but keep fixing bugs and try when possible to add new features.
