### ISSUE TITLE
No password prompt

### ISSUE THREAD

**Issue by drakej** [innotop/innotop#103]
No matter what option I use -p or --password or neither, it will never prompt for the password and instead just loads with a permission error.

**Comment by lefred** [comment]
The is no password prompt, the password needs to follow -p argument like :
> -p password

If you don't want to have the password in the command line, I suggest you to use ~/.my.cnf

**Comment by drakej** [comment]
Sorry I mixed it up with --prompt and I didn't know about the ~/.my.cnf option. Thanks!
