### ISSUE TITLE
innotop not passing password correctly

### ISSUE THREAD

**Issue by drakej** [innotop/innotop#104]
I can't even use innotop at the moment since it doesn't actually pass the provided password to the database. I tested version 1.9.1 and version 1.7.1 against a local and a remote instance of MySQL 5.1.73. I can connect with the same credentials using the "mysql" client program. If I swap "innotop" with "mysql" it works flawlessly and points to the problem being innotop not passing credentials properly.

**Comment by lefred** [comment]
Hi, 

I'm trying to reproduce this, but it seems I can't (I'm not using 5.1, I still need to test with 5.1):

> [fred@localhost innotop]$ ./innotop 
>
> [RO] Dashboard (? for help) localhost, 0.00, 0 QPS, 0/0/0 con/run/cac thds, !loc
> 
> Uptime  MaxSQL  ReplLag  QPS  Cxns  Run  Miss  Lock  Tbls  Repl  SQL
>                                          0.00                       
> localhost: Access denied for user 'root'@'localhost' (using password: NO)

> [fred@localhost innotop]$ ./innotop -pfred
> 
> [RO] Dashboard (? for help) localhost, 51m, 0.13 QPS, 2/1/1 con/run/cac thds, 5.
> 
> Uptime  MaxSQL  ReplLag  QPS   Cxns  Run  Miss  Lock  Tbls  Repl  SQL
>    51m                   0.13     2       0.57     0    69  Off 

What command line are you using ?

**Comment by rlowe** [comment]
I've tested this against 5.1.73 and cannot reproduce it and I've tried both "-pfred" and "--password fred" (both of which work as expected).
