### ISSUE TITLE
Please tag correctly v0.10.0

### ISSUE THREAD

**Issue by Fale** [innotop/innotop#110]
To do so, please execute the following commands:

```
git checkout fd0a1f36ce22bb67be6e35fae9453b396a1fb029
git tag v1.10.0
git push origin v1.10.0
git checkout master
```

Doing so you'll create the v0.10.0 tag, which is correct since that commit is really the tagging og 0.10.0. I can not create a pull request for this, because github does not allow pull requests for tags

**Comment by annunaki2k2** [comment]
Just wanted to add my 2 pence: Yes, please tag this.

Package maintainers really need this... and I'd like to submit an updated ebuild for Gentoo, but that's difficult without the version being tagged.
