### ISSUE TITLE
Runtime error regarding redundant sprintf argument.

### ISSUE THREAD

**Issue by rquadling** [innotop/innotop#122]
Using Cygwin (so potentially a spanner).

`Redundant argument in sprintf at /usr/local/bin/innotop line 6767.`

**Comment by DSpeichert** [comment]
Same here on Arch Linux (latest version).

**Comment by lefred** [comment]
Thank you for your bug report, could you confirm the Perl version you are using ?

**Comment by lefred** [comment]
same on Fedora with Perl 5.22

**Comment by lefred** [comment]
currently, the easiest workaround (to unlock you while working on this) is to edit innotop file and comment line 23:

`#use warnings FATAL => 'all';`

**Comment by rquadling** [comment]
``This is perl 5, version 22, subversion 1 (v5.22.1) built for cygwin-thread-multi``

**Comment by rquadling** [comment]
Ah. That get's me a little further, but then I think I'm screwed. Using Windows as my platform. No sockets, so no ability to connect from Cygwin.

**Comment by DSpeichert** [comment]
Seems to not be a problem in innotop 1.10.0.

**Comment by xerebz** [comment]
Seeing this on ubuntu 16.04

**Comment by Rossmairm** [comment]
Also having this issue with Ubuntu 16.04 using 'This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi'
Exact error is: `PROCESSLIST_NO_IS: Redundant argument in sprintf at /usr/local/bin/innotop line 7661`

**Comment by tulsidas** [comment]
Same error on Debian

`perl 5, version 22, subversion 2 (v5.22.2) built for x86_64-linux-gnu-thread-multi`
`localhost PROCESSLIST: Redundant argument in sprintf at /usr/bin/innotop line 6709.`

this is the code snippet it refers to:
```
#Compares versions like 5.0.27 and 4.1.15-standard-log
sub version_ge {
   my ( $dbh, $target ) = @_;
   my $version = sprintf('%03d%03d%03d', $dbh->{mysql_serverinfo} =~ m/(\d+)/g);
   return $version ge sprintf('%03d%03d%03d', $target =~ m/(\d+)/g);
}
```

**Comment by SerBoox** [comment]
I comment out the line 6027-6031 
`#return sprintf(
   #   $num =~ m/\./ || $n || $force
   #      ? "%.${num_digits}f%s"
   #      : '%d',
   #   $num, ($pad,'k','M','G', 'T')[$n]);`
and 6713
`my $version = 0;#sprintf('%03d%03d%03d', $dbh->{mysql_serverinfo} =~ m/(\d+)/g);`

**Comment by melo** [comment]
The diagnostic message was introduced on perl5.22.0 (see https://metacpan.org/pod/release/RJBS/perl-5.22.0/pod/perldelta.pod#New-Warnings section of perldelta).

It is triggered by passing to `sprintf()` or `printf()` more arguments that are required.

You can fix the code to just pass three arguments above, or alternatively, inside that function, add a `no warnings 'redundant';`.

**Comment by tuxayo** [comment]
Does anyone has a workaround? Like a ENV variable disabling "warnings FATAL => 'all'"

For those still on Ubuntu 16.04 and the impated Debian version for few years.
