### ISSUE TITLE
MySQL 5.7 lock / transaction handling: T and L modes crash 

### ISSUE THREAD

**Issue by cmullican** [innotop/innotop#134]
L crashes with:
Use of uninitialized value in list assignment at /usr/local/bin/innotop line 5535, <FIN> line 5.
T crashes with:
Use of uninitialized value in list assignment at /usr/local/bin/innotop line 5818, <FIN> line 3.

I think D may also have a problem, because it's not showing anything, even though there have been several deadlocks today.

**Comment by lefred** [comment]
duplicate of #109
