### ISSUE TITLE
Inaccurate version

### ISSUE THREAD

**Issue by ilovezfs** [innotop/innotop#139]
Despite the 1.11 tag, version is still reported as 1.10:
https://github.com/innotop/innotop/blob/v1.11/innotop#L25
https://github.com/innotop/innotop/blob/master/innotop#L25

**Comment by lefred** [comment]
a commit was missing, I fixed it, new release is 1.11.1

**Comment by ilovezfs** [comment]
@lefred Thanks. FYI: https://github.com/Homebrew/homebrew-core/pull/1972

**Comment by ilovezfs** [comment]
@lefred hmm
```
Error: innotop: failed
Expected /1\.11\.1/ to match "innotop  Ver 1.11.0\n"
```

**Comment by lefred** [comment]
mmm... seems ok for me:

```
[fred@imac2 ~/workspace/innotop] (master) $ ./innotop --version
innotop  Ver 1.11.1
```

**Comment by lefred** [comment]
Sorry. for a reason I ignore the commit wasn't pushed... I need to verify and add it to the release

**Comment by lefred** [comment]
could you check again ?

**Comment by ilovezfs** [comment]
@lefred https://github.com/Homebrew/homebrew-core/pull/1972 Looks good!
