### ISSUE TITLE
Table 'performance_schema.replication_applier_status' doesn't exist

### ISSUE THREAD

**Issue by Harmit** [innotop/innotop#160]
Innotop looks for a _performance_schema.replication_applier_status_ table that does not exist in our MariaDB 10.2.7 slave database.

```
# mysql --version
mysql  Ver 15.1 Distrib 10.2.7-MariaDB, for Linux (x86_64) using readline 5.1
```

```
# innotop/innotop --version
innotop  Ver 1.11.4
```

```
# innotop/innotop --mode M           
localhost GET_CHANNELS: DBD::mysql::st execute failed: Table 'performance_schema.replication_applier_status' doesn't exist at innotop/innotop line 7552.
```

```
# cat /etc/redhat-release && uname -a
CentOS Linux release 7.3.1611 (Core) 
Linux localhost.localdomain 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
# rpm -qa | grep ^MariaDB     
MariaDB-common-10.2.7-1.el6.x86_64
MariaDB-shared-10.2.7-1.el6.x86_64
MariaDB-compat-10.2.7-1.el6.x86_64
MariaDB-server-10.2.7-1.el6.x86_64
MariaDB-devel-10.2.7-1.el6.x86_64
MariaDB-client-10.2.7-1.el6.x86_64
```

Let me know if you need anything from me.

**Comment by sjalilund** [comment]
Hi,

I've written a fix, but haven't got any MariaDB-instance to test on... 

Can you test with the innotop from my fork/development branch?
https://github.com/sjalilund/innotop

**Comment by Harmit** [comment]
I can confirm that your branch starts up and displays the replication (M) data from 3 different MariaDB v10.x and 5 different MySQL v5.5.x servers at the same time successfully.

**Comment by crewone** [comment]
I can confirm as well it works on MariaDB 10.x
