### ISSUE TITLE
1.15.1 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [innotop/innotop#210]
👋 looks like 1.15.1 release was not completed, ie the release did not get marked as latest release. Raise this issue for awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/192176

**Comment by yoku0825** [comment]
Thank you for reporting.
I released v1.15.1 now!

https://github.com/innotop/innotop/releases/tag/v1.15.1
