### ISSUE TITLE
Incorrect version number

### ISSUE THREAD

**Issue by boutetnico** [innotop/innotop#211]
Just installed latest Innotop from `https://github.com/innotop/innotop/archive/v1.15.1.tar.gz`.

The following command reports an incorrect version.

```bash
innotop --version
innotop  Ver 1.15.0
```

**Comment by boutetnico** [comment]
@yoku0825 thank you for the fix, could you publish a new patch release?

**Comment by yoku0825** [comment]
@boutetnico 
I have set `release 1.15.1` to `tag v1.15.1-2` .
Should I make new `release 1.15.1-2` ?

**Comment by boutetnico** [comment]
Imho, it should be a new tag & release of 1.15.2 to maintain consistency with the versioning used on previous releases.

**Comment by yoku0825** [comment]
Thank you for your knowledge.
I tagged and released 1.15.2.

https://github.com/innotop/innotop/releases/tag/v1.15.2
