### ISSUE TITLE
QPS refers to Questions/sec vs Queries/sec

### ISSUE THREAD

**Issue by lefred** [innotop/innotop#94]
_From [michael....@percona.com](https://code.google.com/u/104748342584108215470/) on March 12, 2013 16:44:49_

What steps will reproduce the problem? 1. read the source on line 1731:
qps                         => { hdr => 'QPS',                 num => 1, label => 'How many queries/sec', },

only line 1731 calls qps as queries/sec, elsewhere code actually references Questions/sec, lines:
1933 - actual QPS calculation
1536 - load calculation What is the expected output? What do you see instead? Elsewhere in the tool QPS refers to Questions. This means that things like SQL_thread events are not included. http://dev.mysql.com/doc/refman/5.5/en/server-status-variables.html#statvar_Queries http://dev.mysql.com/doc/refman/5.5/en/server-status-variables.html#statvar_Questions What version of the product are you using? On what operating system? latest 1.9.0 Please provide any additional information below. I think QPS should really be measuring Queries per second because:
1. that's the common convention when someone says QPS, they mean Queries, not Questions
2. a slave that exists only for backup/binlog will show very low QPS in innotop but in fact it is doing likely a high number of Queries per second.  low QPS in tool makes it appear that server isn't working much (low Load value in innotop, etc)

_Original issue: http://code.google.com/p/innotop/issues/detail?id=81_

**Comment by BartVB** [comment]
Agreed. This is my nr one gripe with innotop and this makes it rather useless on slave nodes.

The fix is rather simple; just replace all references to 'Questions' with 'Queries' in the code.
