### ISSUE TITLE
GTID support in Replication Status

### ISSUE THREAD

**Issue by lefred** [innotop/innotop#95]
_From [lefred.d...@gmail.com](https://code.google.com/u/115097375813850285633/) on July 12, 2013 10:00:14_

It would be great when 5.6 is used to see the GTID information too.

Add the following information from SHOW SLAVE STATUS:

Master_UUID: d9544bcc-e9f2-11e2-b310-0800272e951c
Retrieved_Gtid_Set: d9544bcc-e9f2-11e2-b310-0800272e951c:1-4
Executed_Gtid_Set: d9544bcc-e9f2-11e2-b310-0800272e951c:1-4

_Original issue: http://code.google.com/p/innotop/issues/detail?id=85_

**Comment by rlowe** [comment]
Can we close this now?  The info should be there :)
