### ISSUE TITLE
Use of uninitialized value $mysqlversion in pattern match (m//) at /usr/local/bin/innotop line 473

### ISSUE THREAD

**Issue by lefred** [innotop/innotop#99]
_From [jtin...@etsy.com](https://code.google.com/u/111252479582573427653/) on September 30, 2014 06:34:19_

What steps will reproduce the problem? 1. Percona Server 5.5, use mode T
2. Observe "Use of uninitialized value $mysqlversion in pattern match (m//) at /usr/local/bin/innotop line 473, <FIN> line 1" 3. What is the expected output? What do you see instead? I would expect Transaction view. What version of the product are you using? On what operating system? 1.9.1 EL6 Please provide any additional information below. Patch attached to call get_status_info which populates $mysqlversion

**Attachment:** [patch_uninit.txt](http://code.google.com/p/innotop/issues/detail?id=99)

_Original issue: http://code.google.com/p/innotop/issues/detail?id=99_

**Comment by rlowe** [comment]
It looks like this issue has already been addressed but accidentally applied twice?  

{code}
 5720    my @cxns = get_connections();   
 5721    get_status_info(@cxns);
 5722 
 5723    get_status_info(@cxns);
 5724 
 5725    # If the header is to be shown, buffer pool data is required.
{code}
